CREATE TABLE IF NOT EXISTS USER (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  x VARCHAR(255) NOT NULL,
  truth_social VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTER (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  author VARCHAR(255) NOT NULL,
  creation_date DATE NOT NULL,
  main_headline VARCHAR(255) NOT NULL,
  meta_data TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MEDIA (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type VARCHAR(50) NOT NULL,
  path TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SECTION (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  poster_id INTEGER NOT NULL,
  section_headline VARCHAR(255) NOT NULL,
  section_text TEXT NOT NULL,
  media_id INTEGER,
  FOREIGN KEY (poster_id) REFERENCES POSTER (id) ON DELETE CASCADE,
  FOREIGN KEY (media_id) REFERENCES MEDIA (id) ON DELETE SET NULL
);
