CREATE TABLE IF NOT EXISTS USER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    x TEXT NOT NULL,
    truthSocial TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    author TEXT NOT NULL,
    creationDate TEXT NOT NULL,
    mainHeadline TEXT NOT NULL,
    metaData TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER(id)
);

CREATE TABLE IF NOT EXISTS SECTION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    poster_id INTEGER NOT NULL,
    sectionHeadline TEXT NOT NULL,
    sectionText TEXT NOT NULL,
    media_id INTEGER,
    FOREIGN KEY (poster_id) REFERENCES POSTER(id),
    FOREIGN KEY (media_id) REFERENCES MEDIA(id)
);

CREATE TABLE IF NOT EXISTS MEDIA (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    path TEXT NOT NULL
);